-- Migration: Add UserDocuments table and SystemSettings
-- This script adds the UserDocuments and SystemSettings tables without modifying existing tables

-- Create SystemSettings table
CREATE TABLE IF NOT EXISTS "SystemSettings" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "InterestRatePercentage" numeric(5,2) NOT NULL,
    "AdminFee" numeric(10,2) NOT NULL,
    "MaxLoanPercentage" numeric(5,2) NOT NULL,
    "MinLoanAmount" numeric(10,2) NOT NULL,
    "MaxLoanAmount" numeric(10,2) NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    "LastModifiedBy" text
);

-- Insert default settings if table is empty
INSERT INTO "SystemSettings" (
    "InterestRatePercentage",
    "AdminFee",
    "MaxLoanPercentage",
    "MinLoanAmount",
    "MaxLoanAmount",
    "LastModifiedDate",
    "LastModifiedBy"
)
SELECT 
    5.00,     -- 5% interest rate
    50.00,    -- R50 admin fee
    50.00,    -- Max 50% of monthly earnings
    100.00,   -- Min R100 loan
    10000.00, -- Max R10,000 loan
    NOW(),
    'system'
WHERE NOT EXISTS (SELECT 1 FROM "SystemSettings");

-- Create UserDocuments table
CREATE TABLE IF NOT EXISTS "UserDocuments" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "DocumentType" integer NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FilePath" character varying(500) NOT NULL,
    "FileSize" bigint NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "FileContentBase64" text NULL,
    "Status" integer NOT NULL DEFAULT 0,
    "UploadedAt" timestamp with time zone NOT NULL,
    "VerifiedAt" timestamp with time zone NULL,
    "VerifiedByUserId" text NULL,
    "RejectionReason" character varying(500) NULL,
    "Notes" text NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_UserDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserDocuments_AspNetUsers_UserId" FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserDocuments_AspNetUsers_VerifiedByUserId" FOREIGN KEY ("VerifiedByUserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "IX_UserDocuments_UserId" ON "UserDocuments" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_UserDocuments_Status" ON "UserDocuments" ("Status");
CREATE INDEX IF NOT EXISTS "IX_UserDocuments_DocumentType" ON "UserDocuments" ("DocumentType");
CREATE INDEX IF NOT EXISTS "IX_UserDocuments_UploadedAt" ON "UserDocuments" ("UploadedAt");
CREATE INDEX IF NOT EXISTS "IX_UserDocuments_VerifiedByUserId" ON "UserDocuments" ("VerifiedByUserId");

-- Mark migrations as applied (so EF doesn't try to recreate everything)
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209194909_AddUserDocuments', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209195443_AddBase64ToDocuments', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

-- Display success message
DO $$
BEGIN
    RAISE NOTICE 'UserDocuments table created successfully!';
    RAISE NOTICE 'Migration records added to __EFMigrationsHistory';
END $$;
