-- Add SystemSettings table and default values
-- This script adds the SystemSettings table if it doesn't exist

-- Create SystemSettings table
CREATE TABLE IF NOT EXISTS "SystemSettings" (
    "Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "InterestRatePercentage" numeric(5,2) NOT NULL,
    "AdminFee" numeric(10,2) NOT NULL,
    "MaxLoanPercentage" numeric(5,2) NOT NULL,
    "MinLoanAmount" numeric(10,2) NOT NULL,
    "MaxLoanAmount" numeric(10,2) NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    "LastModifiedBy" text
);

-- Insert default settings if table is empty
INSERT INTO "SystemSettings" (
    "InterestRatePercentage",
    "AdminFee",
    "MaxLoanPercentage",
    "MinLoanAmount",
    "MaxLoanAmount",
    "LastModifiedDate",
    "LastModifiedBy"
)
SELECT 
    5.00,     -- 5% interest rate
    50.00,    -- R50 admin fee
    50.00,    -- Max 50% of monthly earnings
    100.00,   -- Min R100 loan
    10000.00, -- Max R10,000 loan
    NOW(),
    'system'
WHERE NOT EXISTS (SELECT 1 FROM "SystemSettings");

-- Display success message
DO $$
DECLARE
    settings_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO settings_count FROM "SystemSettings";
    RAISE NOTICE 'SystemSettings table ready. % record(s) exist.', settings_count;
END $$;
